apiVersion: v1
kind: Service
metadata:
  name: prodsimapp
  labels:
    app: prodsimapp
spec:
  ports:
  - name: http
    port: 8888
  selector:
    app: prodsimapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodsimapp
spec:
  selector:
    matchLabels:
      app: prodsimapp
  replicas: 2
  template:
    metadata:
      labels:
        app: prodsimapp
    spec:
      containers:
        - name: 72455416d02e
        - image: prodsimapp

          ports:
          - containerPort: 8888